---
- name: "Worker 1.1 Check whether the vm can access to docker.io"
  raw: nslookup index.docker.io
  register: worker_nslookup_docker_io
  failed_when: false
  changed_when: false
  check_mode: false
  environment: {}

- name: "Worker 1.2 Check whether the vm can access to docker.io"
  fail:
    msg: "Unable to access docker.io"
  changed_when: false
  check_mode: false
  environment: {}
  when:
    - worker_nslookup_docker_io.rc != 0

- name: "Worker 2.1 Ensure dev-box is not an worker machines"
  fail:
    msg: "Dev-box should be a separated machine from the cluster."
  when:
    - ansible_control_host_address == ansible_default_ipv4.address

- name: check worker machines' NVIDIA gpu card, drivers and runtime
  include_tasks: ubuntu-nvidia.yml
  when: gpu_type == 'nvidia'

- name: check worker machines' resource requirement
  include_tasks: resource.yml
  when: resource_check

- name: check docker requirement
  include_tasks: ubuntu-docker.yml
  when: docker_check


